"""add experience columns.

Revision ID: 427d62fd8776
Revises: ee8b110b2287
Create Date: 2022-03-15 15:35:50.431502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427d62fd8776'
down_revision = 'ee8b110b2287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('minimum_experience', sa.Integer(), nullable=True))
    op.add_column('positions', sa.Column('maximum_experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'maximum_experience')
    op.drop_column('positions', 'minimum_experience')
    # ### end Alembic commands ###
