"""add table foreign key

Revision ID: 959aa10ce432
Revises: e15e9d7fd4e4
Create Date: 2022-04-08 15:14:08.906977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959aa10ce432'
down_revision = 'e15e9d7fd4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('job_title_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'positions', 'job_titles', ['job_title_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_column('positions', 'job_title_id')
    # ### end Alembic commands ###
