"""add query column.

Revision ID: ee8b110b2287
Revises: 764294dc4737
Create Date: 2022-03-15 14:22:00.019326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8b110b2287'
down_revision = '764294dc4737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('query', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'query')
    # ### end Alembic commands ###
